version : '3.0'

services:
    nginx:
        image: jbeeson/letsencrypt-reverseproxy
        ports:
            - "80:8080"
            - "443:443"
        env_file: .env
        volumes:
            - ssl:/ssl
            - etc_acme:/etc/acme

volumes:
    ssl:
    etc_acme: